const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description:
      "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "comping",
  },
  {
    title: "Modern Loft in Downtown",
    description:
      "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "Boats",
  },
  {
    title: "Mountain Retreat",
    description:
      "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "amazing",
  },
  {
    title: "Historic Villa in Tuscany",
    description:
      "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "amazing",
  },
  {
    title: "Secluded Treehouse Getaway",
    description:
      "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "homes",
  },
  {
    title: "Beachfront Paradise",
    description:
      "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "trending",
  },
  {
    title: "Rustic Cabin by the Lake",
    description:
      "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "moutains",
  },
  {
    title: "Luxury Penthouse with City Views",
    description:
      "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "Boats",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description:
      "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    category: "Boats",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description:
      "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "moutains",
  },
  {
    title: "Historic Canal House",
    description:
      "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    category: "comping",
  },
  {
    title: "Private Island Retreat",
    description:
      "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "homes",
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description:
      "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    category: "trending",
  },
  {
    title: "Historic Brownstone in Boston",
    description:
      "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 2200,
    location: "Boston",
    country: "United States",
    category: "trending",
  },
  {
    title: "Beachfront Bungalow in Bali",
    description:
      "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    category: "comping",
  },
  {
    title: "Mountain View Cabin in Banff",
    description:
      "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1500,
    location: "Banff",
    country: "Canada",
    category: "arctic",
  },
  {
    title: "Art Deco Apartment in Miami",
    description:
      "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
    image: {
      filename: "listingimage",
      url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Miami",
    country: "United States",
    category: "arctic",
  },
  {
    title: "Tropical Villa in Phuket",
    description:
      "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 3000,
    location: "Phuket",
    country: "Thailand",
    category: "arctic",
  },
  {
    title: "Historic Castle in Scotland",
    description:
      "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Scottish Highlands",
    country: "United Kingdom",
    category: "trending",
  },
  {
    title: "Desert Oasis in Dubai",
    description:
      "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 5000,
    location: "Dubai",
    country: "United Arab Emirates",
    category: "trending",
  },
  {
    title: "Rustic Log Cabin in Montana",
    description:
      "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1100,
    location: "Montana",
    country: "United States",
    category: "moutains",
  },
  {
    title: "Beachfront Villa in Greece",
    description:
      "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 2500,
    location: "Mykonos",
    country: "Greece",
    category: "homes",
  },
  {
    title: "Eco-Friendly Treehouse Retreat",
    description:
      "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
  },
  {
    title: "Historic Cottage in Charleston",
    description:
      "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 1600,
    location: "Charleston",
    country: "United States",
    category: "trending",
  },
  {
    title: "Modern Apartment in Tokyo",
    description:
      "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    category: "homes",
  },
  {
    title: "Lakefront Cabin in New Hampshire",
    description:
      "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1200,
    location: "New Hampshire",
    country: "United States",
    category: "comping",
  },
  {
    title: "Luxury Villa in the Maldives",
    description:
      "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 6000,
    location: "Maldives",
    country: "Maldives",
    category: "Boats",
  },
  {
    title: "Ski Chalet in Aspen",
    description:
      "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 4000,
    location: "Aspen",
    country: "United States",
    category: "Boats",
  },
  {
    title: "Secluded Beach House in Costa Rica",
    description:
      "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
    },
    price: 1800,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "trending",
  },
    //Trending
    {
      title:"“The Willow” Stunning location, Amazing views",
      description:"“The Willow” is the ultimate in luxury glamping, set in a very private location with stunning countryside views. ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/c579efd0-3a7a-4132-8bbb-cf7eeadc9806.jpg?im_w=960&im_format=avif",
      },
      price: 14276,
      location: "Farm stay in Pembroke",
      category:"trending",
      country: "United Kingdom",
    },
    {
      title:"Sky Villa-Luxury lakeview Bungalow in City Center",
      description:"Nestled atop a charming hill, with an unobstructed view of the lakes & enchanting city of Udaipur, Sky Villa, a 6-bedroom architectural masterpiece, offers a truly unique living experience.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-983628068535189241/original/6fb13419-22cb-4378-bacc-22fa484869e2.jpeg?im_w=960&im_format=avif",
      },
      price: 25900,
      location: "Entire bungalow in Udaipur",
      category:"trending",
      country: "India",
    },
    {
      title:"Soul Serenity-Pool,Patio-Trek Trails@Trimbakeshwar",
      description:"Enter a world of enchantment and serenity at our stunning abode in Nashik, where the wonders of nature and comfort collide to create a blissful holiday experience",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-777908525036300828/original/8b0f4942-ab59-4286-9961-d30b5e120345.jpeg?im_w=960&im_format=avif",
      },
      price: 13152,
      location: "Entire home in Vadholi",
      category:"trending",
      country: "India",
    },
    {
      title:"AirLoft in the Stauferstadt",
      description:"This great place is anything but usual. A stylish highlight, nested in a park-like complex, our place offers an unforgettable overnight stay experience",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-908611595823138745/original/e2ea2ccc-df2a-4e49-b81d-a508508aae02.jpeg?im_w=960&im_format=avif",
      },
      price: 33549,
      location: "Treehouse in Göppingen",
      category:"trending",
      country: "Germany",
    },
    {
      title:"Waves Seascapes Dapoli",
      description:"Breathtaking sea-view penthouse featuring premium decks with panoramic ocean scenes from a private 360 sqft. balcony & contemporary décor suite with ultimate elegance and luxury at Waves-Seascapes.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-931606072302435846/original/d0e4082f-d7ec-4837-a20d-1204ea6ed9a7.jpeg?im_w=960&im_format=avif",
      },
      price: 4171,
      location: "Entire guest suite in Dapoli",
      category:"trending",
      country: "India",
    },
    {
      title:"Bliss Inn",
      description:"Discover our lakeside retreat at just Rs. 6500/person (weekdays) and Rs. 8000/person (weekends). Nestled in lush tropical beauty, our 3-bedroom house features attached bathrooms, gardens, and a lake-view deck",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/102bd3b3-347c-456f-9e18-df8c93b46676.jpg?im_w=960&im_format=avif",
      },
      price: 5850,
      location: "Entire cottage in Lonavala",
      category:"trending",
      country: "India",
    },
    {
      title:"Emotional healing accommodation in Icheon City",
      description:"It is a whole guita-shaped cottage located in the art village of Icheon. It is a spacious private house with a three-story terrace of the Serra Guitar Cultural Center, famous for its unique facade in the Icheon Ceramic Art village, which blends very well with nature",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/d0e3bb05-a96a-45cf-af92-980269168096.jpg?im_w=960&im_format=avif",
      },
      price: 5626,
      location: "Entire cottage in Sindun-myeon, Icheon-si",
      category:"trending",
      country:"South Korea",
    },
    {
      title:"Anantam C401 4bhk Sea view Penthouse Panjim",
      description:"Nestled gracefully along the enchanting coastline of Goa, this 4BHK sea-facing apartment is a true gem that effortlessly combines opulence with the pristine beauty of nature",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/5314255c-ea99-4b29-9a5c-1ae56f3d9f37.jpg?im_w=720&im_format=avif",
      },
      price: 19569,
      location: "Entire serviced apartment in Panaji",
      category:"trending",
      country:"India",
    },
    {
      title:"Lake Panorama 4BHK With Pool",
      description:"This spectacular 4BHK cozy villa offers a panoramic view of the pristine Pawna Lake. Forget all your worries in this serene and spacious space",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-888826359906290076/original/9899589d-35e1-4d45-9145-1cde779213d5.jpeg?im_w=960&im_format=avif",
      },
      price: 19600,
      location:"Entire home in Kolechafesar",
      category:"trending",
      country: "India",
    },
    {
      title:"Schloss Wimsbach, Austria  South Suite",
      description:"Wimsbach Castle is in a scenically and culturally exceptional location. Guests enjoy nearly six acres (over 2 hectares) of private park as well as the area's outstanding cultural treasures and proximity to Austria's lake district. ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-832355501498041527/original/551de2c9-6981-4222-b21d-75dd8792bd2d.jpeg?im_w=960&im_format=avif",
      },
      price: 10595,
      location: "Room in Bad Wimsbach-Neydharting",
      category:"trending",
      country: "Austria",
    },

    //Rooms
    {
      title:"En-suite Room - Sleeps 3 people - St John's Wood",
      description:"This centrally located En-Suite room is in an apartment which is very well connected just around the corner from the world famous Abbey Road and a few minutes walk to the Beatles crossing & Abbey Road Studios",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/36a7a525-ceb7-4647-92cb-e17e87cb9307.jpg?im_w=960&im_format=avif",
      },
      price: 14326,
      location: "Room in Greater London",
      category:"rooms",
      country: "United Kingdom",
    },
    {
      title: "Bedroom & Bathroom - Riad with Pool",
      description:"Riad Tililaila, located in the heart of the Medina, is an emerald setting in which you will find all the Moroccan lifestyle inviting you to relax",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/b256a9b3-99db-4489-ab93-3660ec178b8b.jpg?im_w=960&im_format=avif",
      },
      price: 6686,
      location:"Room in Marrakech",
      category:"rooms",
      country:"Morocco",
    },
    {
      title:"Thymus - Casa Laurus Nobilis",
      description:"A very bright and comfortable suite with a living room where there is a dining table and a sofa bed; the bedroom is very spacious and bright thanks to the two balconies; the kitchen is equipped with all the useful tools to prepare your lunches; there is a laundry room with a laundry room at your disposal; in the bathroom there is a large and comfortable shower and products for the hygiene of the person and the hair dryer",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/pro_photo_tool/Hosting-20187072-unapproved/original/48f252b2-33b6-47cb-9006-f472b6039c21.JPEG?im_w=960&im_format=avif",
      },
      price: 6622,
      location:"Room in Palermo",
      category:"rooms",
      country: "Italy",
    },
    {
      title: "Winter By Rose Maria & Godwin",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-945204198407478542/original/99059ec9-0be8-4de6-b837-d8a4d3fbdbd5.jpeg?im_w=960&im_format=avif",
      },
      price: 2917,
      location: "Room in Dandenong North",
      category:"rooms",
      country: "Australia",
    },
    {
      title:"Mahalo Villa - Comfy room close to the beach",
      description:"Find your home away from home with Mahalo Villa. This relaxing and comfortable property has 3 separate King Suites each with a private full bathroom and all are just steps away from the shared pool.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/4b5d0713-e601-4490-a45d-81e4cbb8b2e1.jpg?im_w=960&im_format=avif",
      },
      price: 1800,
      location:"Room in Canggu",
      category:"rooms",
      country: " Indonesia",
    },
    {
      title: "Luxury en-suite room with exquisite views",
      description:"The room is one of two available on their own floor level. Each room can accommodate a King size bed or 2 single beds depending on your preference.Each room has it’s own patio, outdoor furniture, umbrella and beautiful views of the Atlantic Ocean",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-39907066/original/4b44b91b-eb39-49a8-93b1-098c2e6f02b7.jpeg?im_w=960&im_format=avif",
      },
      price: 8115,
      location: "Room in Cape Town",
      category:"rooms",
      country: "South Africa",
    },
    {
      title: "Canary whaf",
      description:"Enjoy this well-located Apartment base with quick access to everything.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTI5ODM3OTgxNzA2NTcxNTAzMQ%3D%3D/original/c14ed5b3-88ac-4a14-90f5-68daf8e349cf.jpeg?im_w=960&im_format=avif",
      },
      price: 6311,
      location: "Room in Greater London",
      category:"rooms",
      country: " United Kingdom",
    },
    {
      title:"Ganadala Neighbor Nimman",
      description:"Our cozy private room is located next to Nimman Road. ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1135231142203341926/original/17764dc8-945b-4d18-b140-dad54785aa62.jpeg?im_w=960&im_format=avif",
      },
      price: 3581,
      location: "Room in Tambon Su Thep",
      category:"rooms",
      country: "Thailand",
    },
    {
      title:"Near Beach/Centrall/gym & rooftop",
      description:"Ciao homestay is near Pham Van Dong beach (3 minutes walking), near Linh Ung Pagoda (8 minutes by car), near Tay An Thuong neighborhood (4 minutes by car), there are many famous restaurants and supermarkets around. 8 minutes from city center",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/1832a6d5-79a7-451b-8fa1-4e0b1a99c845.jpg?im_w=960&im_format=avif",
      },
      price: 1324,
      location: "Room in Sơn Trà",
      category:"rooms",
      country: "Vietnam",
    },
    {
      title:"The Bay Beach Villa",
      description:"Riad Tililaila, located in the heart of the Medina, is an emerald setting in which you will find all the Moroccan lifestyle inviting you to relax.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/airflow/Hosting-53301211/original/554ccbd2-eaec-4402-8fb5-5154cc929239.jpg?im_w=960&im_format=avif",
      },
      price: 7363,
      location: "Room in Greater London",
      category:"rooms",
      country: "United Kingdom",
    },
    //Mountains
    {
      title: "Jannat ",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-605371928419351152/original/8711dc45-edaa-452e-8502-628f72784757.jpeg?im_w=960&im_format=avif",
      },
      price: 17746,
      location:"Entire villa in Pimplad Nasik",
      category:"moutains",
      country:"India",
    },
    {
      title:" Cabin on a Hill Near Pawna Lake",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-587439221666468647/original/a3a8257f-f158-4b9f-a9d6-446cf62c8819.jpeg?im_w=720&im_format=avif",
      },
      price: 26200,
      location:"Mahagaon",
      category:"moutains",
      country: "India",
    },
    {
      title:"Caasa Tranquilla",
      description:"Entire cabin in Dhalewadi",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTIzNjE1MDExMTUxNzU5ODEyNw%3D%3D/original/19b0b33e-6a94-43c3-9ec7-48bfb79be8c8.jpeg?im_w=960&im_format=avif",
      },
      price: 6003,
      location:"Dhalewadi",
      category:"moutains",
      country: "India",
    },
    {
      title:"Natures Grove Pavna Valley Villa",
      description:"Room in Dahuli",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1046270679399078512/original/6ad0721b-2201-4ff6-bdbe-391a4db8605d.jpeg?im_w=960&im_format=avif",
      },
      price: 5000,
      location:"Dahuli",
      category:"moutains",
      country: "India",
    },
    {
      title:"Enchanting Dome,Private Plunge Pool,Scenic Getaway",
      description:"Tiny home in Kamshet",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-40333094/original/5e9dedbe-573c-4e9b-ac55-d0be4eac85c2.jpeg?im_w=960&im_format=avif",
      },
      price: 6000,
      location:"Kamshet",
      category:"moutains",
      country:"India",
    },
    {
      title:"Bliss Inn",
      description:"Entire cottage in Lonavala",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/74ebe5c4-037f-4624-b544-195384e15981.jpg?im_w=960&im_format=avif",
      },
      price: 6690,
      location:"Lonavala",
      category:"moutains",
      country:"India",
    },
    {
      title:" Ekostay",
      description:"Entire home in Govitri",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTI4MzIyMDE3NDkyODAyNzYzOQ%3D%3D/original/cf5b4fd1-071d-42b1-8361-91058a6db0e0.jpeg?im_w=960&im_format=avif",
      },
      price: 14560,
      location:"Govitri",
      category:"moutains",
      country:"India",
    },
    {
      title:"Weekend Fables - Shalom",
      description:"Entire villa in Igatpuri",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-686110594962640933/original/b80f2941-7db3-4c4a-b9fe-50b7e7636600.jpeg?im_w=960&im_format=avif",
      },
      price: 13292,
      location: "Igatpuri",
      category:"moutains",
      country: "India",
    },
    {
      title:"Burj Baneria, Lake Pichola Facing Bedroom",
      description:"Private room in nature lodge in Udaipur",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/prohost-api/Hosting-41781376/original/91b8ff9c-5f5e-4743-aefc-55115d25a734.jpeg?im_w=960&im_format=avif",
      },
      price: 7722,
      location:"Udaipur",
      category:"moutains",
      country: "India",
    },
    {
      title:"Earth Shelter/Cave home with Pool & Rooftop Garden",
      description:"Earthen home",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-660600938513754284/original/3263fab4-1ace-4146-87cb-84073a9d9239.jpeg?im_w=960&im_format=avif",
      },
      price: 25487,
      location:"Murbad",
      category:"moutains",
      country:"India",
    },
       //amazing pools
    {
      title: "Monarch 6BR Royal Villa with Turf",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-592536964804693719/original/91fb820b-2afe-41c7-b534-37649d4992a7.jpeg?im_w=1200&im_format=avif",
      },
      price: 26500,
      location: "Entire villa in Aundhe kh., India",
      category:"amazing",
      country: "India",
    },
    {
      title: "StayVista at Nyra Farms w/ Pool, Lawn, BBQ",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1143899547274052615/original/23114ec9-e0af-4230-b804-862a40e4e8b5.jpeg?im_w=960&im_format=avif",
      },
      price: 18750,
      location: "Entire villa in Gorhe, India",
      category:"amazing",
      country: "India",
    },
    {
      title: "4-BR Pool Villa Serene-Game Zone",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-857788805326047302/original/2b440aec-e8fe-4fb6-b80d-a77e9357b424.jpeg?im_w=960&im_format=avif",
      },
      price: 13500,
      location: "Entire home in Lonavala, India",
      category:"amazing",
      country: "India",
    },
    {
      title: "Matoshri Villa",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1156347539884710549/original/96e5b56a-5a0e-4a78-9dcb-6910fa0e8322.jpeg?im_w=960&im_format=avif",
      },
      price: 9000,
      location: "Entire guest house in Lonavala, India",
      category:"amazing",
      country: "India",
    },
    {
      title: "Pool Villa",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-604843151037767955/original/7f9ef8ab-6e87-4411-9bf1-ae8d9b5dfd1a.jpeg?im_w=960&im_format=avif",
      },
      price: 25000,
      location: " Kihim, India",
      category:"amazing",
      country: "India",
    },
    {
      title: " Liwa Guest House",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTMwODUzNjk4NzcyOTQxNjg4Ng%3D%3D/original/f93a1671-1971-43ec-835f-a571b9e66e9f.jpeg?im_w=960&im_format=avif",
      },
      price: 35195,
      location: "Mzeerʻah",
      category:"amazing",
      country: "United Arab Emirates",
    },
    {
      title: "Ramada Tower Sea Views Apartment",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1116575380851079351/original/af0c467c-c73f-4d74-9b18-ee516ba535f5.jpeg?im_w=960&im_format=avif",
      },
      price: 1390,
      location: "Entire rental unit in Batumi",
      category:"amazing",
      country: " Georgia",
    },
    {
      title: "Poseidon’s Perch",
      description:"Entire rental unit in Sarandë",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-907215051510293057/original/6db59051-3514-4cc5-a9ab-6e109d3c5f25.jpeg?im_w=960&im_format=avif",
      },
      price: 4320,
      location: "Sarandë",
      category:"amazing",
      country: "Albania",
    },
    {
      title: "Perch",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-907215051510293057/original/c5ff9fe3-07af-4502-ae3a-d4a9ac4b76fe.jpeg?im_w=720&im_format=avif",
      },
      price: 5890,
      location:"Sarande",
      category:"amazing",
      country: "Albania",
    },
    {
      title: "Ananya- Pet-friendly Pool Villa, Party Deck, Games",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-720084776646494960/original/b6db3004-e745-448c-9262-6548085bc49c.jpeg?im_w=720&im_format=avif",
      },
      price: 1800,
      location: "Entire villa in Karjat",
      category:"amazing",
      country: "India",
    },
      //camping
    {
      title:"A-Frame:Nirja|Open-air Bathtub|Boutique Resort",
      description:"Tiny home",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1286208323180296244/original/59132e17-641d-468c-88a6-289952403d08.jpeg?im_w=960&im_format=avif",
      },
      price: 6499,
      location:"Mandrem",
      category:"comping",
      country:"India",
    },
    {
      title:"Luxury Tropical Pool Villa - Siolim Door",
      description:"Entire home ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/8dfd1593-6fef-4c9c-b3a2-7ca0e489db9b.jpg?im_w=960&im_format=avif",
      },
      price: 10950,
      location:"Entire home in Siolim",
      category:"comping",
      country:"India",
    },
    {
      title:"Amreena Farmhouse",
      description:"Farm stay",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/952d9196-f836-4975-b20d-4061f1901d1e.jpg?im_w=960&im_format=avif",
      },
      price: 2840,
      location:"Avalas",
      category:"comping",
      country:"India",
    },
    {
      title:"Mohraan Farms - Cozy Tents in a Food Forest",
      description:"It's a vibrant Food Forest that embodies a deep love for nature and sustainable living, cultivated over four decades by dedicated caretakers.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-53000025/original/e4843b1e-baad-4e47-bfde-cf7b3f1f095f.jpeg?im_w=960&im_format=avif",
      },
      price: 2000,
      location:"Farm stay in Shahapur",
      category:"comping",
      country:"India",
    },
    {
      title:"Farmstay at Parule",
      description:"Room in Parule",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/e06bd86e-1dd6-4e5f-ad2f-6c62b21d6174.jpg?im_w=960&im_format=avif",
      },
      price: 9500,
      location:"Parule",
      category:"comping",
      country:"India",
    },
    {
      title:"Mohraan Farms -Feel the Forest - Villa (E&W)",
      description:"Farm stay",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-52293285/original/231c0b70-ecfc-466f-9baf-a98ea57a405f.jpeg?im_w=960&im_format=avif",
      },
      price: 7200,
      location:"Shahapur",
      category:"comping",
      country:"India",
    },
    {
      title:"Heritage Organic farm-Room no1 attached washroom",
      description:"Ours is a home with a warm welcoming feeling with several sit outs, a  fireplace and hammocks.Redstone Organic Farm is eco,people and animal friendly rustic home. Experience authentic country living ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/3d41b4b4-aa67-4c23-90b8-0ad2a4f57532.jpg?im_w=960&im_format=avif",
      },
      price: 3800,
      location:"Mahabaleshwar",
      category:"comping",
      country:"India",
    },
    {
      title:"Tree house Usha",
      description:"In every walk in with nature one receives far more than he seeks. Visited the pace of nature with the mesmerizing freshess of pure air along with mist at Hillock Mountains. Enjoyed the the sunrise over a wide-open country field, morning rain glistening on forest trees, and snow-covered mountaintop peaks. Recommended to all nature lovers.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-751206971626894382/original/e0607051-4fe3-43d4-b808-ea9422113003.jpeg?im_w=960&im_format=avif",
      },
      price: 5309,
      location:"Treehouse in Hiriwadunna",
      category:"comping",
      country:"Sri Lanka",
    },
    {
      title:"Tree house",
      description:"Private room in treehouse in Kozhikode",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/4a2a8c72-cb5b-4088-9e39-cc359aa40cf3.jpg?im_w=960&im_format=avif",
      },
      price: 3500,
      location:"Kozhikode",
      category:"comping",
      country:"India",
    },
    {
      title:"Galkadawala Forest Lodge, Habarana.",
      description:"2 Forest Lodges nestled in the centre of the Cultural Triangle and 3 Wildlife Parks. Habarana.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-4390065/original/1158f852-0a38-46d2-935d-c4687dbb223a.jpeg?im_w=960&im_format=avif",
      },
      price: 7757,
      location:"Room in Habarana",
      category:"comping",
      country:"Sri lanka",
    },
    //arctic

    {
      title: "Ollero Eco Lodge",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/fb860347-88b9-4a1a-acfe-d518f3f77072.jpg?im_w=960&im_format=avif",
      },
      price: 58460,
      location: "Entire cabin in Rovaniemi",
      category:"arctic",
      country: "Finland",
    },
    {
      title: "Fjälluggla Cottage - Cabin Fjälluggla",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-46487748/original/9e4c806e-dbad-4186-a0c6-bd75adc0c068.jpeg?im_w=960&im_format=avif",
      },
      price: 9210,
      location:"Entire chalet in Blattniksele ",
      category:"arctic",
      country:"Sweden",
    },
    {
      title: "Villa Red House Arctic Circle",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/8ec575eb-f582-42b2-a74b-c7e5876c7af8.jpg?im_w=720&im_format=avif",
      },
      price: 70000,
      location: "Rovaniemi",
      category:"arctic",
      country: "Finland",
    },
    {
      title: "Lake location. Fishing, snowmobile, hiking",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/184c80d3-d919-4905-8635-71e78f71e964.jpg?im_w=960&im_format=avif",
      },
      price: 8990,
      location: "Entire villa in Överkalix Ö",
      category:"arctic",
      country: "Sweden",
    },
    {
      title:"Arctic Aurora HideAway",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1022281845356402607/original/057e4086-7628-4fa5-b760-e52ca2d0acf7.jpeg?im_w=960&im_format=avif",
      },
      price: 8800,
      location:"Rovaniemi",
      category:"arctic",
      country:"Finland",
    },
    {
      title:"Kentura Guesthouse ",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-792821836975611802/original/3a45bc1a-d692-4ac5-8831-3f696e0d8374.jpeg?im_w=960&im_format=avif",
      },
      price: 9800,
      location:"Entire guest house in Rovaniemi",
      category:"arctic",
      country: "Finland",
    },
    {
      title:"Lapland holiday cottage",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-27541046/original/4b172617-1821-461e-9ed4-5130a24a4b00.jpeg?im_w=960&im_format=avif",
      },
      price: 1780,
      location: "Entire cabin in Rovaniemi",
      category:"arctic",
      country: "Finland",
    },
    {
      title: "Cozy cottage by the lake - Rukatunturi",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/7f65f567-d00d-4368-af1e-2cde7ff885e9.jpg?im_w=960&im_format=avif",
      },
      price: 8570,
      location: "Entire cottage in Kuusamo",
      category:"arctic",
      country: "Finland",
    },
    {
      title:"Hillagammi",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/441bf0ac-a272-4aad-9cef-326b94d7aa1a.jpg?im_w=720&im_format=avif",
      },
      price: 23450,
      location:"Utsjoki,",
      category:"arctic",
      country: "Artic",
    },
    {
      title:"Cabin 2",
      description:" Exclusive glamping in the ocean gap",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-660544775047324041/original/6652512e-7e7d-4898-add9-0e78c6b283cf.jpeg?im_w=960&im_format=avif",
      },
      price: 1970,
      location: "Skjøttholmen",
      category:"arctic",
      country:  "Norway",
    },

      //boats
    {
      title:"Yacht holidays Maldives",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/cc1b161e-6ea9-4a75-9d2f-0f28e9308406.jpg?im_w=960&im_format=avif",
      },
      price: 172339,
      location:"Boat in Malé ",
      category:"Boats",
      country: "Maldives",
    },
    {
      title: "Broward USA 110 Ft Superyacht Cachée",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/755533da-3118-4599-b733-28ae119870f5.jpg?im_w=960&im_format=avif",
      },
      price: 373929,
      location: "Boat in Sattahip",
      category:"Boats",
      country: " Thailand",
    },
    {
      title: "Deluxe Double With Sea View",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1220131180443524293/original/5ffc7db9-31c8-45ce-aa9e-6b33e63903b2.jpeg?im_w=960&im_format=avif",
      },
      price: 32613,
      location: "Private room in boat in Thành phố Hạ Long",
      category:"Boats",
      country: "Vietnam",
    },
    {
      title: "Breathtaking Cruise",
      description:"Private room in nature lodge in Bangkok",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/39857344-4762-4e41-a7a6-ba9fc6f9b557.jpg?im_w=960&im_format=avif",
      },
      price: 2143,
      location: "Private room in nature lodge in Bangkok",
      category:"Boats",
      country: "Thailand",
    },
    {
      title: "Lee Yam",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/ca2bfbd0-ac1f-473a-968b-b1363323b25b.jpg?im_w=960&im_format=avif",
      },
      price: 10230,
      location: "Boat in Ashdod",
      category:"Boats",
      country: "Israel",
    },
    {
      title:"Enjoy the stars on a luxury from 68 yacht",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1198693160936857571/original/9a7909ec-5084-442f-844b-b4c1355febc4.jpeg?im_w=960&im_format=avif",
      },
      price: 154612,
      location:"Boat in Girne",
      category:"Boats",
      country: "Girne",
    },
    {
      title: "Luxury yacht accommodation",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1098603605779711444/original/b7351271-584c-46ea-a2cd-6c0e6a953900.jpeg?im_w=960&im_format=avif",
      },
      price: 56312,
      location:"Boat in Dubai",
      category:"Boats",
      country: "United Arab Emirates",
    },
    {
      title:"Maha Bhetra",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-913360509561636373/original/fe9f63fa-8abe-4545-9f63-9ba198e336a8.jpeg?im_w=960&im_format=avif",
      },
      price: 466160,
      location:"Boat in Tambon Mai Khao",
      category:"Boats",
      country:"Thailand",
    },
    {
      title: "Luxurious Sunseeker 62 ft. Manhattan - Fethiye",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-46270272/original/5975f114-f315-4a42-8407-03abf77980e9.jpeg?im_w=960&im_format=avif",
      },
      price: 132500,
      location: "Boat in Fethiye",
      category:"Boats",
      country: "Turkey",
    },
    {
      title:"Maldives Luxury Yacht Private Charter",
      description:"",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/63901e76-2eca-49bd-be9b-d56695a9fb56.jpg?im_w=960&im_format=avif",
      },
      price: 474300,
      location: "Boat in Malé,",
      category:"Boats",
      country: "Maldives",
    },
    //Domes
    {
      title:"Geodesic Dome - Tea Plantation",
      description:"FeaturesQueen Size Bed, Transparent front bay window and sunroof,Free Wi-Fi,Tea Coffee Maker, Ensuite bathroom",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTE0NTMxMTU1NDQxMjIyNTQ2Ng%3D%3D/original/0c449d1f-a3c0-4124-9e65-90556abd061e.jpeg?im_w=960&im_format=avif",
      },
      price: 7499,
      location: "Wayanad",
      category:"Domes",
      country: "India",
    },
    {
      title:"Geodesic Domes in Manali Hamta.",
      description:"Discover the gorgeous landscape that surrounds this place to stay.We welcome you to our premiere geodesic domes and hobbit house at Hamta, these domes and hobbit are another sustainable luxury stay started by the founder of Manali Igloo Stay. The first Igloo stay of India",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/7b43d02d-bc24-4271-b90e-29fcdd43bd56.jpg?im_w=960&im_format=avif",
      },
      price: 9999,
      location: "Kullu",
      category:"Domes",
      country: "India",
    },
    {
      title:"Bastiat Stays| FlowNest Dome In Kasol",
      description:"Escape to this unique riverside dome nestled in the heart of nature. Enjoy breathtaking, uninterrupted views of the flowing river and surrounding mountains from the comfort of your cozy dome",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTI1NDk0NjQyMjI4MzA1MDQyMA%3D%3D/original/dfded05d-1529-4f1e-be7c-1a1b2fc407ae.jpeg?im_w=960&im_format=avif",
      },
      price:7999,
      location: "Kasol",
      category:"Domes",
      country: "India",
    },
    {
      title:"Magical Treehouse",
      description:"Experience the magic of eco-friendly living among the treetops.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/00deac7d-e259-4bde-b7e3-d1c99e9f72a9.jpg?im_w=960&im_format=avif",
      },
      price: 8741,
      location: "Lagos",
      category:"Domes",
      country: " Portugal",
    },
    {
      title:"Sahar Wadi Rum",
      description:"Reconnect with nature at this unforgettable escape",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1117627316721738691/original/1bff0fbe-d092-4d6e-9f03-be7f998fbf80.jpeg?im_w=960&im_format=avif",
      },
      price: 5221,
      location: " Rum Village",
      category:"Domes",
      country: "Jordan",
    },
    {
      title:"Thenor Dome Villa Luxury Suites",
      description:"There is only 1 unit, the whole place is your private area.",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1165485311766615218/original/1770da97-6f67-427a-b61c-5ded1c98802c.jpeg?im_w=960&im_format=avif",
      },
      price: 13155,
      location: "Mae Raem",
      category:"Domes",
      country: "Thailand",
    },
    //Iconic cities
    {
      title:"Breathtaking Mountain views in cozy Birdbox",
      description:"Enjoy the relaxed and comfortable enclosure of the Birdbox. Sleep right beside nature and its amazing  surroundings. Lay down and look at the spectacular mountains all around you",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/23a60113-a16d-4cd6-bf5a-a2f352eb4f4e.jpg?im_w=960&im_format=avif",
      },
      price: 22571,
      location: "Gaular",
      category:"iconic",
      country: "Norway",
    },
    {
      title:"Once in a Life Time View ~5mins walk to Train&Boat",
      description:"THE BEST VIEW OF BANGKOK!! ⭐5 star service from the HIGHEST RATED HOST in this building⭐",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6Nzc2ODAyMDc1NDk2NjQ3MTU2/original/ef81e95f-a0c9-40ab-adaa-afcc67a264fc.jpeg?im_w=960&im_format=avif",
      },
      price: 7361,
      location: "Khet Bang Rak",
      category:"iconic",
      country: "Thailand",
    },
    {
      title:"Fen House 2BR *Jacuzzi Private Cool *Near Beach",
      description:"WELCOME TO FEN HOUSE!❤️",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/hosting/Hosting-1126839634398201811/original/53511e53-aa22-43e0-b5f6-c2e38a98f30e.jpeg?im_w=960&im_format=avif",
      },
      price: 10181,
      location: "Sơn Trà",
      category:"iconic",
      country: "Vietnam",
    },
    {
      title:"Self contained studio with private courtyard",
      description:"This lovely self contained studio features kitchenette, bathroom and courtyard and it has been fitted out with all you need for a comfortable stay just minutes walk to the city, with transport, shopping, cafes, restaurants and galleries all around you",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/f75099d1-0b17-4e8a-8e3f-c07c96ca41d3.jpg?im_w=960&im_format=avif",
      },
      price: 7656,
      location: "Chippendale",
      category:"iconic",
      country: " Australia",
    },
    {
      title:"Burj Khalifa Rooftop Infinity Pool 64th Floor",
      description:"Experience a blend of luxury and cinematic style in our 30th floor stunning two-bedroom apartment at the HollyWood inspired Paramount Midtown Hotel & Residences, featuring breathtaking Burj Khalifa views. ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-1281224160699988747/original/16a9c8a6-b0da-42fc-a846-4e82749753d5.jpeg?im_w=960&im_format=avif",
      },
      price: 32786,
      location: " Dubai",
      category:"iconic",
      country: " United Arab Emirates",
    },
    {
      title:"Luxury & Breathtaking Eiffel & Paris Amazing View",
      description:"Indulge in the ultimate Parisian experience at our luxurious apartment. ",
      image:{
        filename: "listingimage",
        url:"https://a0.muscache.com/im/pictures/miso/Hosting-631154213461762756/original/9e1dc69d-c64f-4052-8dad-6f089fa04b6e.jpeg?im_w=960&im_format=avif",
      },
      price: 145765,
      location: "Paris",
      category:"iconic",
      country: "France",
    },
    


  ];
  
  module.exports = { data: sampleListings };